[package]
name = "chainx-cli"
version = "1.0.4"
authors = ["koushiro <koushiro.cqx@gmail.com>"]
edition = "2018"

[[bin]]
name = "chainx-cli"
path = "src/bin/main.rs"

[dependencies]
structopt = "0.2"
failure = { version = "0.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parity-codec = { version = "3.5", features = ["derive"] }
web3 = "0.8"

[dependencies.substrate-primitives]
git = "https://github.com/paritytech/substrate"
tag = "v1.0.0"
