[package]
name = "chainx-cli"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"
description = "Rust Command Line Interface for ChainX 2.0 based on substrate-subxt"
readme = "README.md"
license = "LICENSE"
default-run="chainx-cli"

[[bin]]
name = "chainx-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "chainx-verify"
path = "src/bin/verify/mod.rs"

[[bin]]
name = "chainx-monitor"
path = "src/bin/monitor.rs"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6.2", features = ["attributes"] }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive", "full"] }
log = "0.4.0"
env_logger = "0.8.1"
hex = "0.4"
jsonrpsee = { version = "0.1", features = ["ws"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
subxt = { package="substrate-subxt", path="./lib3rd/substrate-subxt"}

sc-cli = { version = "0.8.0", optional = true }

frame-support = "2.0.0"
sp-authority-discovery = "2.0.0"
sp-consensus-babe = "0.8.0"
sp-core = "2.0.0"
sp-finality-grandpa = "2.0.0"
sp-keyring = "2.0.0"
sp-runtime = "2.0.0"

pallet-indices = "2.0.0"
pallet-im-online = "2.0.0"

[features]
default = ["sc-cli"]

