[package]
name = "chainx-cli"
version = "1.0.6"
authors = ["ChainX <https://github.com/chainx-org>"]
edition = "2018"

[[bin]]
name = "xli"
path = "src/bin/main.rs"

[dependencies]
structopt = "0.2"
failure = { version = "0.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web3 = "0.8"

primitive-types = { version = "0.5", features = ["serde", "rustc-hex"] }
