[package]
name = "chainx-cli"
version = "1.0.7"
authors = ["ChainX <https://github.com/chainx-org>"]
description = "A command-line tool of ChainX"
edition = "2018"

[[bin]]
name = "chainx-cli"
path = "src/bin/main.rs"

[dependencies]
structopt = "0.3"
failure = { version = "0.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web3 = "0.8"
substrate-primitives = { git = "https://github.com/chainpool/substrate", branch = "chainx-master" }

# Feature `internal`
codec = { package = "parity-codec", version = "3.5", optional = true }
sr-primitives = { git = "https://github.com/chainpool/substrate", branch = "chainx-master", optional = true }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", branch = "chainx-master", optional = true }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", branch = "chainx-master", optional = true }
chainx-runtime = { path = "../ChainX/runtime", optional = true }
chainx-primitives = { path = "../ChainX/primitives", optional = true }
xassets = { package = "xrml-xassets-assets", path = "../ChainX/xrml/xassets/assets", optional = true }
xstaking = { package = "xrml-xmining-staking", path = "../ChainX/xrml/xmining/staking", optional = true }
xtokens = { package = "xrml-xmining-tokens", path = "../ChainX/xrml/xmining/tokens", optional = true }
xmultisig = { package = "xrml-xmultisig", path = "../ChainX/xrml/xmultisig", optional = true }

[features]
default = []
internal = [
    "codec",
    "sr-primitives",
    "system",
    "support",
    "chainx-runtime",
    "chainx-primitives",
    "xassets",
    "xstaking",
    "xtokens",
    "xmultisig",
]
