[package]
name = "chainx-cli"
version = "2.0.0-rc6"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6.2", features = ["attributes"] }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive", "full"] }
env_logger = "0.7.1"
hex = "0.4"
structopt = "0.3"

sc-cli = "0.8.0"

sp-application-crypto = "2.0.0"
sp-authority-discovery = "2.0.0"
sp-consensus-aura = "0.8.0"
sp-core = "2.0.0"
sp-finality-grandpa = "2.0.0"
sp-keyring = "2.0.0"
sp-runtime = "2.0.0"
sp-std = "2.0.0"

pallet-indices = "2.0.0"
pallet-im-online = "2.0.0"

# remove this when a new version is released
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt" }
