[package]
name = "chainx-cli"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6.2", features = ["attributes"] }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive", "full"] }
serde_json = "1.0"
env_logger = "0.7.1"
jsonrpsee = { version = "0.1.0", features = ["ws"] }
hex = "0.4"
log = "0.4"
structopt = "0.3"
subxt = { package = "substrate-subxt", version = "0.13" }

sc-cli = "0.8.0"

sp-application-crypto = "2.0.0"
sp-authority-discovery = "2.0.0"
sp-consensus-aura = "0.8.0"
sp-core = "2.0.0"
sp-finality-grandpa = "2.0.0"
sp-keyring = "2.0.0"
sp-runtime = "2.0.0"
sp-std = "2.0.0"

pallet-indices = "2.0.0"
pallet-im-online = "2.0.0"

xpallet-mining-staking = { git = "https://github.com/chainx-org/ChainX", branch = "develop-2.0" }
xp-genesis-builder = { git = "https://github.com/chainx-org/ChainX", branch = "develop-2.0" }
