[package]
name = "chainx-cli"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"
description = "Rust Command Line Interface for ChainX 2.0 based on substrate-subxt"
readme = "README.md"
license = "LICENSE"

[[bin]]
name = "chainx-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "chainx-verify"
path = "src/bin/verify/mod.rs"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6.2", features = ["attributes"] }
env_logger = "0.8.1"
hex = "0.4"
jsonrpsee = { version = "0.1", features = ["ws"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
subxt = { package = "substrate-subxt", version = "0.15.0" }

sc-cli = { version = "*", optional = true }

frame-support = "3.0.0"
sp-authority-discovery = "3.0.0"
sp-consensus-babe = "0.9.0"
sp-core = "3.0.0"
sp-finality-grandpa = "3.0.0"
sp-keyring = "3.0.0"
sp-runtime = "3.0.0"

pallet-indices = "3.0.0"
pallet-im-online = "3.0.0"
codec = { package = "parity-scale-codec", version = "2.0", default-features = false, features = ["derive", "full"] }

[features]
default = ["sc-cli"]
