on: [push, pull_request]

name: Continuous integration

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-03-01
        target: wasm32-unknown-unknown
        profile: minimal
        override: true
        components: rustfmt, rust-src, clippy

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Format
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test --verbose

    - name: Compile
      run: cargo test --no-run
