on: [push, pull_request]

name: Continuous integration

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

        - name: Install Rust deps
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly-2020-09-30
            override: true
            components: rustfmt, clippy

        - name: Rustfmt
        - uses: actions-rs/cargo@v1
          with:
            command: fmt
            args: --all -- --check

        - name: Clippy
        - uses: actions-rs/cargo@v1
          with:
            command: clippy
            args: -- -D warnings

        - name: Check
        - uses: actions-rs/cargo@v1
          with:
            command: check

        - name: Test
        - uses: actions-rs/cargo@v1
          with:
            command: test
